version: "3"
services:
  app:
    build: ./dockerfiles/app
    volumes:
      - ${APP_CODE_PATH_HOST}:/app
    ports:
      - "${PHOENIX_PORT}:4001"
    environment:
      - PHOENIX_VERSION=${PHOENIX_VERSION}
    depends_on:
      - postgres
    tty: true
    stdin_open: true
  postgres:
    build: ./dockerfiles/db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - es_postgres:/var/lib/postgresql/data
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./priv/swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/swagger.json
    ports:
      - "${SWAGGER_UI_PORT}:8080"
volumes:
  es_postgres:
    driver: "local"
